name: flutter_ctrip
description: A new Flutter application of ctrip

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_color_plugin: ^0.0.2
  flutter_swiper: ^1.1.6
  http: ^0.12.0+4
  flutter_webview_plugin: ^0.3.11
  flutter_staggered_grid_view: ^0.3.0
  flutter_spinkit: ^4.1.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - images/type_channelplane.png
    - images/type_district.png
    - images/type_food.png
    - images/type_hotel.png
    - images/type_huodong.png
    - images/type_shop.png
    - images/type_sight.png
    - images/type_ticket.png
    - images/type_travelgroup.png
    - images/type_channelgroup.png
    - images/type_channelgs.png
    - images/type_channeltrain.png
    - images/type_cruise.png
    - images/lvpai_search_tag.png
    - images/lvpai_issue_sight.png
    - images/lvpai_search_list.png
    - images/lvpai_issue_position.png
    - images/user1.png
    - images/xiaoxi_white.png
    - images/xiecheng.png
    - images/xiecheng_active.png
    - images/xiaoxi_grey.png
    - images/mude.png
    - images/mude_active.png
    - images/lvpai.png
    - images/lvpai_active.png
    - images/wode.png
    - images/wode_active.png
    - images/grid-nav-items-jhj.png
    - images/grid-nav-items-minsu.png
    - images/grid-nav-items-hotel.png
    - images/grid-nav-items-flight.png
    - images/grid-nav-items-train.png
    - images/grid-nav-items-travel.png
    - images/grid-nav-items-dingzhi.png
    - images/yuyin.png
    - images/sousuo.png
    - images/lvxiang.png
    - images/kefu.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  fonts:
    - family: PingFang
      fonts:
#        - asset: fonts/PingFang-Regular.ttf
#        - asset: fonts/PingFang-Italic.ttf
        - asset: fonts/PingFang_Bold.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
